services:
  - type: web
    name: mchelpie
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
